windows_task:
  name: "Windows"
  timeout_in: 20m
  compute_engine_instance:
    image_project: cirrus-images
    image: family/windows-docker-builder
    platform: windows
    cpu: 2
    memory: 4G
  matrix:
    - name: "Windows/containerd-1.7"
      env:
        ctrdVersion: 1.7.3
  env:
    CGO_ENABLED: 0
  build_script:
    - mkdir "C:\Windows\system32\config\systemprofile\AppData\Local\Temp\"
    - powershell hack/configure-windows-ci.ps1
    - refreshenv
    - go install .\cmd\nerdctl\
    - go test -v ./cmd/...
