freebsd_task:
  name: FreeBSD
  timeout_in: 20m
  compute_engine_instance:
    image_project: freebsd-org-cloud-dev
    image: family/freebsd-13-0
    platform: freebsd
    cpu: 2
    memory: 4G
  env:
    NERDCTL_RUN_ARGS: --net none dougrabson/freebsd-minimal:13.1 echo "Nerdctl is up and running."
  install_script:
    - pkg install -y go containerd runj
  test_script:
    - daemon -o containerd.out containerd
    - go test -v ./pkg/...
    - cd cmd/nerdctl
    - sudo go run . run $NERDCTL_RUN_ARGS | grep running
# TODO: run `go test -v ./cmd/...`

windows_task:
  name: "Windows"
  timeout_in: 20m
  compute_engine_instance:
    image_project: cirrus-images
    image: family/windows-docker-builder
    platform: windows
    cpu: 2
    memory: 4G
  matrix:
    - name: "Windows/containerd-1.6"
      env:
        ctrdVersion: 1.6.8
  env:
    CGO_ENABLED: 0
  build_script:
    - mkdir "C:\Windows\system32\config\systemprofile\AppData\Local\Temp\"
    - powershell hack/configure-windows-ci.ps1
    - refreshenv
    - go install .\cmd\nerdctl\
    - go test -v ./cmd/...
