---
run:
  concurrency: 6
  timeout: 5m
linters:
  disable-all: true
  enable:
    - depguard
    - gofmt
    - goimports
    - govet
    - ineffassign
    - misspell
    - nakedret
    - prealloc
    - typecheck
    # - asciicheck
    # - bodyclose
    # - dogsled
    # - dupl
    # - errcheck
    # - errorlint
    # - exhaustive
    # - exhaustivestruct
    # - exportloopref
    # - funlen
    # - gci
    # - gochecknoglobals
    # - gochecknoinits
    # - gocognit
    # - goconst
    # - gocritic
    # - gocyclo
    # - godot
    # - godox
    # - goerr113
    # - gofumpt
    # - goheader
    # - golint
    # - gomnd
    # - gomodguard
    # - goprintffuncname
    # - gosec (gas)
    - gosimple  # (megacheck)
    # - interfacer
    # - lll
    # - maligned
    # - nestif
    # - nlreturn
    # - noctx
    # - nolintlint
    - revive
    # - rowserrcheck
    # - scopelint
    # - sqlclosecheck
    - staticcheck
    - stylecheck
    # - testpackage
    # - tparallel
    - unconvert
    # - unparam
    - unused
    # - whitespace
    # - wrapcheck
    # - wsl
linters-settings:
  gocritic:
    enabled-checks:
      # Diagnostic
      - appendAssign
      - argOrder
      - badCond
      - caseOrder
      - codegenComment
      - commentedOutCode
      - deprecatedComment
      - dupArg
      - dupBranchBody
      - dupCase
      - dupSubExpr
      - exitAfterDefer
      - flagDeref
      - flagName
      - nilValReturn
      - offBy1
      - sloppyReassign
      - weakCond
      - octalLiteral

      # Performance
      - appendCombine
      - equalFold
      - hugeParam
      - indexAlloc
      - rangeExprCopy
      - rangeValCopy

      # Style
      - assignOp
      - boolExprSimplify
      - captLocal
      - commentFormatting
      - commentedOutImport
      - defaultCaseOrder
      - docStub
      - elseif
      - emptyFallthrough
      - emptyStringTest
      - hexLiteral
      - ifElseChain
      - methodExprCall
      - regexpMust
      - singleCaseSwitch
      - sloppyLen
      - stringXbytes
      - switchTrue
      - typeAssertChain
      - typeSwitchVar
      - underef
      - unlabelStmt
      - unlambda
      - unslice
      - valSwap
      - wrapperFunc
      - yodaStyleExpr

      # Opinionated
      - builtinShadow
      - importShadow
      - initClause
      - nestingReduce
      - paramTypeCombine
      - ptrToRefParam
      - typeUnparen
      - unnamedResult
      - unnecessaryBlock

  depguard:
    rules:
      # pkg files must not depend on cobra nor anything in cmd
      pkg:
        files:
          - "**/pkg/**/*.go"
        deny:
          - pkg: "github.com/spf13/cobra"
            desc: "pkg must not depend on cobra"
          - pkg: "github.com/spf13/pflag"
            desc: "pkg must not depend on pflag"
          - pkg: "github.com/spf13/viper"
            desc: "pkg must not depend on viper"
          - pkg: "github.com/containerd/nerdctl/v2/cmd"
            desc: "pkg must not depend on any cmd files"
      no-patent:
        deny:
          - pkg: "github.com/hashicorp/golang-lru/arc/v2"
            desc: "patented (https://github.com/hashicorp/golang-lru/blob/arc/v2.0.7/arc/arc.go#L18)"

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - linters:
        - revive
      text: "unused-parameter"

output:
  sort-results: true
