# Renders the "flaky test dashboard" from the raw data collected by flaky-report.sh.
#
# Input (through --slurpfile and --arg):
#   $executions: [{sha, id, name, conclusion, url, at}]              one entry per job execution
#   $findings:   [{id, kind, tests}]                                 one entry per reported class
#   $notes:      [string]                                            caveats about the collection itself
#   $footer:     string                                              extra markdown for the methodology
#   $docsURL:    string                                              where the project documents flakiness
# Output: {markdown, digest, data}
#
# Note: the same test may be reported several times by a single job (the integration suite is
# invoked once per variant: non-flaky, flaky, ipv6), and both a parent test and its subtests may
# be reported. Occurrences are therefore counted per (commit, job configuration, kind, top-level
# test), so that a single bad job execution counts once.

def normalize: gsub("\\s+"; " ") | sub("^ +"; "") | sub(" +$"; "");

# Table cells are pipe-separated, and what goes in them comes from a job log or a workflow file:
# a stray pipe would break the table, and a stray backtick would break out of the code span the
# cell is rendered in. The collector rejects both in a test name; this is the second line.
def mdcell: tostring | .[0:200] | gsub("\\|"; "\\|") | gsub("`"; "\u0027");

def toplevel: split("/")[0];

def day: split("T")[0];

def clamp($n): if $n < 0 then 0 elif $n > 10 then 10 else $n end;

def pct($num; $denom): if $denom > 0 then (100 * $num / $denom | round) else 0 end;

# A ten characters wide horizontal bar, so that the job failure rates can be compared at a glance.
# Anything that did happen at all gets at least one block: "rare" and "never" must not look alike.
def bar($ratio):
  clamp(if $ratio > 0 then ([($ratio * 10) | round, 1] | max) else 0 end) as $filled
  | (if $filled > 0 then "█" * $filled else "" end)
    + (if $filled < 10 then "░" * (10 - $filled) else "" end);

def plural($n; $word): "\($n) \($word)\(if $n == 1 then "" else "s" end)";

($maxTests | tonumber) as $maxTests
| ($maxLinks | tonumber) as $maxLinks
| ($executions | map(.name |= normalize)) as $execs
| ($execs | map({key: .id, value: .}) | from_entries) as $byID
| ($execs | map(.sha) | unique | length) as $commits
| (
    $findings
    | map(
        . as $finding
        | ($byID[$finding.id] // empty) as $run
        | $finding.tests[]
        | {
            test: .,
            top: toplevel,
            kind: $finding.kind,
            job: $run.name,
            url: $run.url,
            at: $run.at,
            sha: $run.sha
          }
      )
  ) as $occurrences
| (
    $occurrences
    | group_by(.top)
    | map(
        . as $group
        | ($group | group_by([.sha, .job, .kind]) | map(.[0]) | sort_by(.at) | reverse) as $unique
        | {
            test: $group[0].top,
            cases: ($group | map(.test) | unique),
            failing: ($unique | map(select(.kind == "failing")) | length),
            flaky: ($unique | map(select(.kind == "flaky")) | length),
            commits: ($group | map(.sha) | unique | length),
            jobs: ($group | map(.job) | unique),
            occurrences: $unique
          }
        | .total = (.failing + .flaky)
      )
    | sort_by(-.total, .test)
  ) as $tests
| (
    $execs
    | group_by(.name)
    | map({
        job: .[0].name,
        executions: length,
        failures: (map(select(.conclusion == "failure")) | length),
        urls: [.[] | select(.conclusion == "failure") | .url]
      })
    | map(select(.failures > 0))
    | sort_by(-(.failures / .executions), -.failures, .job)
  ) as $jobs
| ($tests[:$maxTests]) as $top
| {
    data: {
      repo: $repo,
      branch: $branch,
      since: $since,
      until: $now,
      commits: $commits,
      executions: ($execs | length),
      tests: $tests,
      jobs: $jobs
    },

    markdown: (
      [
        "<!-- Generated by Soigneur (mod/soigneur): do not edit by hand. -->",
        "## Flaky test dashboard",
        "",
        "Failures reported by the CI on [`\($branch)`](https://github.com/\($repo)/commits/\($branch))"
          + " between \($since | day) and \($now | day)"
          + " — \(plural($commits; "commit")) with CI results, \(plural($execs | length; "job execution")).",
        "",
        (
          if ($notes | length) == 0 then
            ""
          else
            (["> [!NOTE]"] + ($notes | map("> - " + .)) + [""]) | join("\n")
          end
        ),

        "### Tests",
        "",
        (
          if ($tests | length) == 0 then
            "No test-level failure was reported in this window. 🎉"
          else
            [
              "| Test | Occurrences | Recovered on retry | Commits affected | Configurations | Last seen |",
              "| --- | --: | --: | --- | --: | --- |"
            ]
            + (
              $top
              | map(
                  "| `\(.test | mdcell)`"
                    + (if (.cases | length) > 1 then " <sup>\(plural(.cases | length; "case"))</sup>" else "" end)
                    + " | \(.total)"
                    + " | \(.flaky)"
                    + " | \(.commits)/\($commits)"
                    + " | \(.jobs | length)"
                    + " | [\(.occurrences[0].at | day)](\(.occurrences[0].url)) |"
                )
            )
            + (
              if ($tests | length) > ($top | length) then
                ["", "_\(plural(($tests | length) - ($top | length); "less frequently reported test")) omitted._"]
              else
                []
              end
            )
            | join("\n")
          end
        ),
        "",
        (
          $top
          | map(
              "<details><summary><code>\(.test)</code> — \(plural(.total; "occurrence"))</summary>\n"
                + "\n"
                + (
                  [
                    "| When | Job configuration | Test | Outcome |",
                    "| --- | --- | --- | --- |"
                  ]
                  + (
                    .occurrences[:$maxLinks]
                    | map(
                        "| [\(.at | day)](\(.url))"
                          + " | `\(.job | mdcell)`"
                          + " | `\(.test | mdcell)`"
                          + " | \(if .kind == "flaky" then "recovered on retry" else "failed" end) |"
                      )
                  )
                  | join("\n")
                )
                + (
                  if (.occurrences | length) > $maxLinks then
                    "\n\n_\(plural((.occurrences | length) - $maxLinks; "older occurrence")) omitted._"
                  else
                    ""
                  end
                )
                + "\n\n</details>"
            )
          | join("\n")
        ),
        "",

        "### Job configurations",
        "",
        "_Every job, test or not: a job that fails without any test failing is usually an"
          + " environment, timeout, or infrastructure problem._",
        "",
        (
          if ($jobs | length) == 0 then
            "Every job execution succeeded in this window. 🎉"
          else
            [
              "| Job configuration | Failure rate | Failed | Executions | Recent failures |",
              "| --- | --- | --: | --: | --- |"
            ]
            + (
              $jobs
              | map(
                  "| `\(.job | mdcell)`"
                    + " | `\(bar(.failures / .executions))` \(pct(.failures; .executions))%"
                    + " | \(.failures)"
                    + " | \(.executions)"
                    + " | \([.urls[:3] | to_entries[] | "[\(.key + 1)](\(.value))"] | join(" ")) |"
                )
            )
            | join("\n")
          end
        ),
        "",

        "<details><summary>How this is collected</summary>",
        "",
        "This dashboard is generated by",
        "[Soigneur](https://github.com/containerd/nerdctl/tree/main/mod/soigneur),",
        "which aggregates the GitHub Actions annotations that the test jobs attach to themselves.",
        "No database, test artifact, or server is involved, so the window that can be reported on is",
        "limited by the retention of the check runs (90 days, by default).",
        "",
        "- **Occurrences**: how many (commit × job configuration) executions reported the test as failing.",
        "- **Recovered on retry**: occurrences where the test did pass when it was retried",
        "  (`gotestsum --rerun-fails`). Those are flaky beyond a doubt. The others are either flaky,",
        "  or consistently broken.",
        (if $footer == "" then "" else $footer end),
        "",
        (
          if $docsURL == "" then
            ""
          else
            "See \($docsURL) to reproduce, fix, or quarantine a flaky test."
          end
        ),
        "",
        "</details>",
        "",
        (if $runURL == "" then "" else "Generated by [this run](\($runURL))." end)
      ]
      | join("\n")
    ),

    digest: (
      if ($tests | length) == 0 then
        "No test-level failure was reported on `\($branch)` over the last \(plural($commits; "commit"))."
      else
        "\(plural($tests | length; "test")) reported over the last \(plural($commits; "commit")) on `\($branch)`"
          + ", topped by " + ([$tests[:3][] | "`\(.test)` (\(.total))"] | join(", ")) + "."
      end
    )
  }
