version: "2"

run:
  issues-exit-code: 2
  modules-download-mode: readonly
  allow-parallel-runners: true
  allow-serial-runners: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

linters:
  default: all
  disable:
    - cyclop
    - exhaustruct
    - funlen
    - godox
    - nonamedreturns
  settings:
    depguard:
      rules:
        main:
          files:
            - $all
          allow:
            - $gostd
            - github.com/containerd/nerdctl/mod/tigron
            - github.com/creack/pty
            - golang.org/x/sync
            - golang.org/x/term
            - gotest.tools/v3
            - github.com/rs/zerolog
            - github.com/rs/zerolog/log
            - go.uber.org/goleak
    staticcheck:
      checks:
        - all
  exclusions:
    generated: disable

formatters:
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/containerd)
        - localmodule
      no-inline-comments: true
      no-prefix-comments: true
      custom-order: true
    gofumpt:
      extra-rules: true
    golines:
      max-len: 100
      tab-len: 4
      shorten-comments: true
  enable:
    - gci
    - gofumpt
    - golines
  exclusions:
    generated: disable
