# This currently test docker and nerdctl on windows (w/o canary)
# Structure is in to allow testing nerdctl on linux as well, though more work is required to make it functional.
name: job-test-in-host

on:
  workflow_call:
    inputs:
      timeout:
        required: true
        type: number
      runner:
        required: true
        type: string
      canary:
        required: false
        default: false
        type: boolean
      no-hyperv:
        required: false
        default: false
        type: boolean
      binary:
        required: false
        default: nerdctl
        type: string
      go-version:
        required: true
        type: string
      docker-version:
        required: true
        type: string
      windows-containerd-version:
        required: true
        type: string
      windows-containerd-sha:
        required: true
        type: string
      linux-containerd-version:
        required: true
        type: string
      linux-containerd-sha:
        required: true
        type: string
      linux-containerd-service-sha:
        required: true
        type: string
      windows-cni-version:
        required: true
        type: string
      linux-cni-version:
        required: true
        type: string
      linux-cni-sha:
        required: true
        type: string

env:
  GOTOOLCHAIN: local

jobs:
  test:
    name: |
      ${{ inputs.binary != 'nerdctl' && format('{0} < ', inputs.binary) || '' }}
      ${{ contains(inputs.runner, 'ubuntu') && ' linux' || ' windows' }}
      ${{ contains(inputs.runner, 'arm') && '(arm)' || '' }}
      ${{ contains(inputs.runner, '22.04') && '(old ubuntu)' || '' }}
      ${{ inputs.canary && ' (canary)' || '' }}
    timeout-minutes: ${{ inputs.timeout }}
    runs-on: "${{ inputs.runner }}"
    defaults:
      run:
        shell: bash

    env:
      SHOULD_RUN: "yes"
      GO_VERSION: ${{ inputs.go-version }}
      # Both Docker and nerdctl on linux need rootful right now
      WITH_SUDO: ${{ contains(inputs.runner, 'ubuntu') }}
      WINDOWS_CONTAINERD_VERSION: ${{ inputs.windows-containerd-version }}
      WINDOWS_CONTAINERD_SHA: ${{ inputs.windows-containerd-sha }}
      LINUX_CONTAINERD_VERSION: ${{ inputs.linux-containerd-version }}
      LINUX_CONTAINERD_SHA: ${{ inputs.linux-containerd-sha }}

    steps:
      - name: "Init: checkout"
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10  # v6.0.3
        with:
          fetch-depth: 1
          persist-credentials: false

      - if: ${{ inputs.no-hyperv }}
        name: "Init (no-hyperv): Disable Hyper-V"
        run: |
          printf "NO_HYPERV=1\n" >> "$GITHUB_ENV"

      - if: ${{ inputs.canary }}
        name: "Init (canary): retrieve latest go and containerd"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          INPUTS_RUNNER: ${{ inputs.runner }}
        run: |
          latest_go="$(. ./hack/provisioning/version/fetch.sh; go::canary::for::go-setup)"
          latest_containerd="$(. ./hack/provisioning/version/fetch.sh; github::project::latest "containerd/containerd")"

          [ "$latest_go" == "" ] || \
            printf "GO_VERSION=%s\n" "$latest_go" >> "$GITHUB_ENV"

          if [[ "${INPUTS_RUNNER}" == *windows* ]]; then
            containerd_version="$WINDOWS_CONTAINERD_VERSION"
          else
            containerd_version="$LINUX_CONTAINERD_VERSION"
          fi
          [ "${latest_containerd:1}" == "$containerd_version" ] || {
            if [[ "${INPUTS_RUNNER}" == *windows* ]]; then
              printf "WINDOWS_CONTAINERD_VERSION=%s\n" "${latest_containerd:1}" >> "$GITHUB_ENV"
              printf "WINDOWS_CONTAINERD_SHA=canary is volatile and I accept the risk\n" >> "$GITHUB_ENV"
            else
              printf "LINUX_CONTAINERD_VERSION=%s\n" "${latest_containerd:1}" >> "$GITHUB_ENV"
              printf "LINUX_CONTAINERD_SHA=canary is volatile and I accept the risk\n" >> "$GITHUB_ENV"
            fi
          }
          if [ "$latest_go" == "" ] && [ "${latest_containerd:1}" == "$containerd_version" ]; then
            echo "::warning title=No canary::There is currently no canary versions to test. Steps will not run.";
            printf "SHOULD_RUN=no\n" >> "$GITHUB_ENV"
          fi

      - if: ${{ env.SHOULD_RUN == 'yes' }}
        name: "Init: install go"
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c  # v6.4.0
        with:
          go-version: ${{ env.GO_VERSION }}
          check-latest: true

      # XXX RUNNER_OS and generally env is too unreliable
      # - if: ${{ env.RUNNER_OS == 'Linux' }}
      - if: ${{ contains(inputs.runner, 'ubuntu') && env.SHOULD_RUN == 'yes' }}
        name: "Init (linux): prepare host"
        run: |
          if [ "${{ contains(inputs.binary, 'docker') }}" == true ]; then
            echo "::group:: configure cdi and experimental for docker"
            sudo mkdir -p /etc/docker
            sudo jq -n '.features.cdi = true | .experimental = true' | sudo tee /etc/docker/daemon.json
            echo "::endgroup::"
            echo "::group:: downgrade docker to the specific version we want to test (${INPUTS_DOCKER_VERSION})"
            sudo apt-get update -qq
            sudo apt-get install -qq ca-certificates curl
            sudo install -m 0755 -d /etc/apt/keyrings
            sudo cp ./hack/provisioning/gpg/docker /etc/apt/keyrings/docker.asc
            sudo chmod a+r /etc/apt/keyrings/docker.asc
            echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
              $(. /etc/os-release && echo "${UBUNTU_CODENAME:-$VERSION_CODENAME}") stable" \
              | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
            sudo apt-get update -qq
            sudo apt-get install -qq --allow-downgrades docker-ce=${INPUTS_DOCKER_VERSION} docker-ce-cli=${INPUTS_DOCKER_VERSION}
            sudo systemctl restart docker
            echo "::endgroup::"
          else
            # FIXME: this is missing runc (see top level workflow note about the state of this)
            echo "::group:: install dependencies"
            sudo ./hack/provisioning/linux/containerd.sh uninstall
            ./hack/provisioning/linux/containerd.sh rootful "$LINUX_CONTAINERD_VERSION" "amd64" "$LINUX_CONTAINERD_SHA" "${INPUTS_LINUX_CONTAINERD_SERVICE_SHA}"
            sudo ./hack/provisioning/linux/cni.sh uninstall
            ./hack/provisioning/linux/cni.sh install "${INPUTS_LINUX_CNI_VERSION}" "amd64" "${INPUTS_LINUX_CNI_SHA}"
            echo "::endgroup::"

            echo "::group:: build nerctl"
            go install ./cmd/nerdctl
            echo "$HOME/go/bin" >> "$GITHUB_PATH"
            # Since tests are going to run root, we need nerdctl to be in a PATH that will survive `sudo`
            sudo cp "$(which nerdctl)" /usr/local/bin
            echo "::endgroup::"
          fi

          # Register QEMU (tonistiigi/binfmt)
          # `--install all` will only install emulation for architectures that cannot be natively executed
          # Since some arm64 platforms do provide native fallback execution for 32 bits,
          # armv7 emulation may or may not be installed, causing variance in the result of `uname -m`.
          # To avoid that, we explicitly list the architectures we do want emulation for.
          echo "::group:: install binfmt"
          docker run --quiet --privileged --rm tonistiigi/binfmt --install linux/amd64
          docker run --quiet --privileged --rm tonistiigi/binfmt --install linux/arm64
          docker run --quiet --privileged --rm tonistiigi/binfmt --install linux/arm/v7
          echo "::endgroup::"

          # FIXME: remove expect when we are done removing unbuffer from tests
          echo "::group:: installing test dependencies"
          sudo add-apt-repository ppa:criu/ppa -y
          sudo apt-get install -qq expect criu
          echo "::endgroup::"

          # This ensures that bridged traffic goes through netfilter
          sudo modprobe br-netfilter
        env:
          INPUTS_DOCKER_VERSION: ${{ inputs.docker-version }}
          INPUTS_LINUX_CONTAINERD_SERVICE_SHA: ${{ inputs.linux-containerd-service-sha }}
          INPUTS_LINUX_CNI_VERSION: ${{ inputs.linux-cni-version }}
          INPUTS_LINUX_CNI_SHA: ${{ inputs.linux-cni-sha }}

      - if: ${{ contains(inputs.runner, 'windows') && env.SHOULD_RUN == 'yes' }}
        name: "Init (windows): prepare host"
        env:
          ctrdVersion: ${{ env.WINDOWS_CONTAINERD_VERSION }}
          ctrdSha: ${{ env.WINDOWS_CONTAINERD_SHA }}
          INPUTS_WINDOWS_CNI_VERSION: ${{ inputs.windows-cni-version }}
        run: |
          # Install WinCNI
          echo "::group:: install wincni"
          GOPATH=$(go env GOPATH) WINCNI_VERSION=${INPUTS_WINDOWS_CNI_VERSION} ./hack/provisioning/windows/cni.sh
          echo "::endgroup::"

          # Install containerd
          echo "::group:: install containerd"
          powershell hack/provisioning/windows/containerd.ps1
          echo "::endgroup::"

          # Install nerdctl
          echo "::group:: build nerctl"
          go install ./cmd/nerdctl
          echo "::endgroup::"

          choco install jq

      - if: ${{ env.SHOULD_RUN == 'yes' }}
        name: "Init: install dev tools"
        run: |
          echo "::group:: make install-dev-tools"
          make install-dev-tools
          echo "::endgroup::"

      # ipv6 is tested only on linux
      - if: ${{ contains(inputs.runner, 'ubuntu') && env.SHOULD_RUN == 'yes' }}
        name: "Run (linux): integration tests (IPv6)"
        run: |
          . ./hack/github/action-helpers.sh
          github::md::h2 "ipv6" >> "$GITHUB_STEP_SUMMARY"

          ./hack/test-integration.sh -test.target=${INPUTS_BINARY} -test.only-ipv6
        env:
          INPUTS_BINARY: ${{ inputs.binary }}

      - if: ${{ env.SHOULD_RUN == 'yes' }}
        name: "Run: integration tests"
        run: |
          . ./hack/github/action-helpers.sh
          github::md::h2 "non-flaky" >> "$GITHUB_STEP_SUMMARY"

          ./hack/test-integration.sh -test.target=${INPUTS_BINARY} -test.only-flaky=false
        env:
          INPUTS_BINARY: ${{ inputs.binary }}

      # FIXME: this must go
      - if: ${{ env.SHOULD_RUN == 'yes' }}
        name: "Run: integration tests (flaky)"
        run: |
          . ./hack/github/action-helpers.sh
          github::md::h2 "flaky" >> "$GITHUB_STEP_SUMMARY"

          ./hack/test-integration.sh -test.target=${INPUTS_BINARY} -test.only-flaky=true
        env:
          INPUTS_BINARY: ${{ inputs.binary }}
