# This job runs any subsidiary linter not part of golangci (shell, yaml, etc)
name: job-lint-other

on:
  workflow_call:
    inputs:
      timeout:
        required: true
        type: number
      runner:
        required: true
        type: string

env:
  GOTOOLCHAIN: local

jobs:
  lint-other:
    name: "yaml | shell"
    timeout-minutes: ${{ inputs.timeout }}
    runs-on: ${{ inputs.runner }}
    defaults:
      run:
        shell: bash

    steps:
      - name: "Init: checkout"
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10  # v6.0.3
        with:
          fetch-depth: 1
          persist-credentials: false

      - name: "Run: yaml"
        run: |
          make lint-yaml

      - name: "Run: shell"
        run: |
          make lint-shell
