# This pipeline purpose is solely meant to run a subset of our test suites against a kubernetes cluster
name: kubernetes

on:
  push:
    branches:
      - main
      - 'release/**'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  linux:
    runs-on: "ubuntu-24.04"
    timeout-minutes: 40
    env:
      ROOTFUL: true
    steps:
      - uses: actions/checkout@v4.2.1
        with:
          fetch-depth: 1
      - name: "Run Kubernetes integration tests"
        # See https://github.com/containerd/nerdctl/blob/main/docs/testing/README.md#about-parallelization
        run: |
          ./hack/build-integration-kubernetes.sh
          sudo ./_output/nerdctl exec nerdctl-test-control-plane bash -c -- 'export TMPDIR="$HOME"/tmp; mkdir -p "$TMPDIR"; cd /nerdctl-source; /usr/local/go/bin/go test -p 1 ./cmd/nerdctl/... -test.only-kubernetes'
